services:
  web:
    image: ghcr.io/dvantourout/hiking_app:main
    ports:
      - "8000:8000"
    env_file: ".env"
  db:
    image: postgis/postgis:17-3.5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
